### ISSUE TITLE
Error at rand_orth function defined in GAN.jl

### ISSUE THREAD

**Issue by Nerdyvedi** [f-t-s/CGD#1]
function rand_orth(m, n)
  @assert(m>=n)
  A = randn(m,n)
  return Matrix(qr(A).Q)
end

qr is not defined. I could not find any definition anywhere

**Comment by f-t-s** [comment]
Sorry about that, qr refers to the [qr decomposition ](https://en.wikipedia.org/wiki/QR_decomposition) and is located in the package LinearAlgebra. I added the importing of the package.

Thanks for letting me know about that! Please let me know if there are any further issues.
